const express=require("express")
const app=express()
const cp=require("cookie-parser")
app.use(cp())
app.use(express.static(__dirname,{index:"cookie2.html"}))
app.get("/next",(req,res)=>{
    res.cookie("fname",req.query.fn)
    res.cookie("lname",req.query.ln)
    res.cookie("pwd",req.query.pw)
    res.redirect("/admin")
})
app.get("/admin",(req,res)=>{
    res.clearCookie("lname")
    res.send(`Welcome ${req.cookies.fname} ${req.cookies.lname} password is: ${req.cookies.pwd} `)
})
app.listen(5002)